services:
  - type: web
    name: weather-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: OPENWEATHER_API_KEY
        sync: false